spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?severTimezone=UTC
    username: root
    password: 123456
  jdbc:
    template:
      query-timeout: 3 #查询超时属性

#配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml